### ISSUE TITLE
5.0.6 not work

### ISSUE THREAD

**Issue by chris93111** [sbaudoin/sonar-ansible#33] opened 2021-03-31 19:25 UTC
hello 

With ansible-lint 5.0.6 they are many error with analysis

WARNING  Listing 43 violation(s) that are fatal
WARN: Invalid issue syntax, ignoring: ../../playbook/test.yml:8: risky-shell-pipe
WARN: Errors happened during analysis:

**Comment by sbaudoin** [comment] 2021-07-25 12:59
Looks like it is due to #34

**Comment by sbaudoin** [comment] 2021-07-25 20:34
So yes, I confirm this is due to #34. The bottom line is that the rules have new ids so it should just be a matter of adding new rules. I close the issue as a duplicate of #34.

**Closed by sbaudoin** 2021-07-25 20:34 UTC
